// Single source of truth for reading texts, imported by the client (Texts tab + reader).
// Each text carries its own glossary: keyed by the LOWERCASED surface form as it appears
// in the paragraphs, so a tapped word can be looked up without any lemmatization.
// ponytail: photos use picsum seeds so they always load; swap for curated Unsplash URLs if topical images matter.
export const texts = [
  {
    id: "daten",
    category: "Gesellschaft",
    level: "B2",
    featured: true,
    photo: "https://picsum.photos/seed/daten/600/400",
    title: "Das Geschäft mit unseren Daten",
    desc: "Wie Tech-Konzerne mit persönlichen Daten Geld verdienen.",
    paragraphs: [
      `Apps sammeln große Mengen persönlicher Daten – aus denen Tech-Unternehmen Nutzerprofile erstellen und mit denen sie viel Geld verdienen können. Effektiver Datenschutz ist auch in der EU schwer durchzusetzen.`,
      `Eine App wie ein Messenger ist schnell installiert. Bei der Abfrage, ob persönliche Daten genutzt werden dürfen, klicken viele einfach auf „Ja" – und erlauben damit zum Beispiel WhatsApp, alle Kontakte des Telefons zu speichern. Doch das ist noch nicht alles. Denn große Tech-Unternehmen kontrollieren komplette Infrastrukturen. Digitalexperte Jan Penfrat erklärt: Daten werden über das Telefon selbst, das Betriebssystem und die Apps gesammelt. Bei Google sind das zum Beispiel Google-Mail, Kontakte, Kalender – und Google Maps, „wo die Aufenthaltsorte der Menschen im Minutentakt mit aufgezeichnet werden können."`,
      `Dazu kommen Annahmen der Unternehmen selbst. „Wenn sie also Zugriff haben auf meine Ortungsdaten und wissen, wo ich mich üblicherweise nachts aufhalte, können sie davon ausgehen: Das ist meine Wohnadresse", erklärt Penfrat. Aus den Nutzungsdaten und den Annahmen können individuelle Profile erstellt werden. „Das ist ein riesiger, globaler Milliardenmarkt, auf dem persönliche Datenprofile von Menschen einfach verhökert werden," so Penfrat.`,
      `Dabei hat die EU vergleichsweise strenge Datenschutzregeln. Mehrfach wurden Konzerne wie Apple, Meta oder Google zu Strafen von Hunderten Millionen Euro verurteilt. Doch das ist nicht hoch genug, meint Penfrat. Und eine wirklich effektive Kontrolle durch die EU ist nicht einfach: Die Tech-Konzerne besitzen globale Infrastrukturen, große finanzielle Ressourcen und komplexe Geschäftsmodelle. Dazu kommt Europas Abhängigkeit: Cloud-Dienste, Betriebssysteme, Plattformen und KI-Infrastruktur kommen zu großen Teilen von US-Unternehmen.`,
      `Nutzenden rät Penfrat, sich zu fragen, womit im jeweiligen Fall gerade Geld verdient wird. Es gilt: „Wenn ich nicht bezahle, dann bin ich das Produkt." Kostenlose Dienste werden also mit Daten bezahlt. Daher lohnt sich die Suche nach Alternativen – wie nach entsprechenden Handys oder sozialen Netzwerken, so der Experte. Gleichzeitig fordert Penfrat stärkere Regulierungen und mehr politischen Mut. „Denn wir müssen es hier aufnehmen mit den größten und mächtigsten Konzernen, die die Menschheit je gesehen hat – und die stehen leider nicht auf unserer Seite."`,
    ],
    glossary: {
      geschäft: { lemma: "das Geschäft", pos: "noun", en: "business, deal" },
      daten: { lemma: "die Daten", pos: "noun (pl.)", en: "data" },
      sammeln: { lemma: "sammeln", pos: "verb", en: "to collect" },
      datenschutz: { lemma: "der Datenschutz", pos: "noun", en: "data protection" },
      durchzusetzen: { lemma: "durchsetzen", pos: "verb", en: "to enforce" },
      erlauben: { lemma: "erlauben", pos: "verb", en: "to allow" },
      speichern: { lemma: "speichern", pos: "verb", en: "to store, to save" },
      kontrollieren: { lemma: "kontrollieren", pos: "verb", en: "to control" },
      betriebssystem: { lemma: "das Betriebssystem", pos: "noun", en: "operating system" },
      annahmen: { lemma: "die Annahme", pos: "noun", en: "assumptions" },
      wohnadresse: { lemma: "die Wohnadresse", pos: "noun", en: "home address" },
      verurteilt: { lemma: "verurteilen", pos: "verb", en: "to convict, to sentence" },
      strafen: { lemma: "die Strafe", pos: "noun", en: "penalties, fines" },
      abhängigkeit: { lemma: "die Abhängigkeit", pos: "noun", en: "dependence" },
      regulierungen: { lemma: "die Regulierung", pos: "noun", en: "regulations" },
      verhökert: { lemma: "verhökern", pos: "verb", en: "to sell off (colloq.)" },
      mächtigsten: { lemma: "mächtig", pos: "adjective", en: "most powerful" },
      konzerne: { lemma: "der Konzern", pos: "noun", en: "corporations" },
    },
    // Full static lookup for every word in this text (keyed by lowercased surface form).
    // Featured vocab above stays in `glossary` (dotted underline); this covers the rest so no API is needed.
    words: {
      abfrage: { lemma: "die Abfrage", pos: "noun", en: "query, prompt" },
      abhängigkeit: { lemma: "die Abhängigkeit", pos: "noun", en: "dependence" },
      alle: { lemma: "alle", pos: "pronoun", en: "all" },
      alles: { lemma: "alles", pos: "pronoun", en: "everything" },
      also: { lemma: "also", pos: "adverb", en: "so, therefore" },
      alternativen: { lemma: "die Alternative", pos: "noun", en: "alternatives" },
      annahmen: { lemma: "die Annahme", pos: "noun", en: "assumptions" },
      app: { lemma: "die App", pos: "noun", en: "app" },
      apple: { lemma: "Apple", pos: "noun (proper)", en: "Apple" },
      apps: { lemma: "die App", pos: "noun", en: "apps" },
      auch: { lemma: "auch", pos: "adverb", en: "also, too" },
      auf: { lemma: "auf", pos: "preposition", en: "on, to" },
      aufenthaltsorte: { lemma: "der Aufenthaltsort", pos: "noun", en: "whereabouts, locations" },
      aufgezeichnet: { lemma: "aufzeichnen", pos: "verb", en: "recorded" },
      aufhalte: { lemma: "sich aufhalten", pos: "verb", en: "(I) stay, spend time" },
      aufnehmen: { lemma: "aufnehmen", pos: "verb", en: "to take on, to take up" },
      aus: { lemma: "aus", pos: "preposition", en: "from, out of" },
      ausgehen: { lemma: "ausgehen (von)", pos: "verb", en: "to assume" },
      bei: { lemma: "bei", pos: "preposition", en: "at, with, during" },
      beispiel: { lemma: "das Beispiel", pos: "noun", en: "example" },
      besitzen: { lemma: "besitzen", pos: "verb", en: "to own, to possess" },
      betriebssystem: { lemma: "das Betriebssystem", pos: "noun", en: "operating system" },
      betriebssysteme: { lemma: "das Betriebssystem", pos: "noun", en: "operating systems" },
      bezahle: { lemma: "bezahlen", pos: "verb", en: "(I) pay" },
      bezahlt: { lemma: "bezahlen", pos: "verb", en: "paid" },
      bin: { lemma: "sein", pos: "verb", en: "(I) am" },
      cloud: { lemma: "die Cloud", pos: "noun", en: "cloud" },
      dabei: { lemma: "dabei", pos: "adverb", en: "in doing so, thereby" },
      daher: { lemma: "daher", pos: "adverb", en: "therefore, hence" },
      damit: { lemma: "damit", pos: "adverb", en: "with it, so that" },
      dann: { lemma: "dann", pos: "adverb", en: "then" },
      das: { lemma: "das", pos: "article/pronoun", en: "the, that" },
      datenprofile: { lemma: "das Datenprofil", pos: "noun", en: "data profiles" },
      datenschutzregeln: { lemma: "die Datenschutzregel", pos: "noun", en: "data protection rules" },
      davon: { lemma: "davon", pos: "adverb", en: "from it, of it" },
      dazu: { lemma: "dazu", pos: "adverb", en: "in addition, on top of that" },
      dem: { lemma: "dem", pos: "article", en: "the (dative)" },
      den: { lemma: "den", pos: "article", en: "the" },
      denen: { lemma: "denen", pos: "pronoun", en: "which, whom" },
      denn: { lemma: "denn", pos: "conjunction", en: "because, for" },
      der: { lemma: "der", pos: "article", en: "the" },
      des: { lemma: "des", pos: "article", en: "of the" },
      die: { lemma: "die", pos: "article", en: "the" },
      dienste: { lemma: "der Dienst", pos: "noun", en: "services" },
      digitalexperte: { lemma: "der Digitalexperte", pos: "noun", en: "digital expert" },
      doch: { lemma: "doch", pos: "adverb", en: "but, however" },
      durch: { lemma: "durch", pos: "preposition", en: "through, by" },
      dürfen: { lemma: "dürfen", pos: "verb", en: "to be allowed to, may" },
      effektive: { lemma: "effektiv", pos: "adjective", en: "effective" },
      effektiver: { lemma: "effektiv", pos: "adjective", en: "effective" },
      ein: { lemma: "ein", pos: "article", en: "a, an" },
      eine: { lemma: "eine", pos: "article", en: "a, an" },
      einfach: { lemma: "einfach", pos: "adjective/adverb", en: "simple, simply" },
      entsprechenden: { lemma: "entsprechend", pos: "adjective", en: "corresponding, suitable" },
      erklärt: { lemma: "erklären", pos: "verb", en: "explains" },
      erstellen: { lemma: "erstellen", pos: "verb", en: "to create" },
      erstellt: { lemma: "erstellen", pos: "verb", en: "created" },
      es: { lemma: "es", pos: "pronoun", en: "it" },
      eu: { lemma: "die EU", pos: "noun (proper)", en: "the EU" },
      euro: { lemma: "der Euro", pos: "noun", en: "euro" },
      europas: { lemma: "Europa", pos: "noun (proper)", en: "Europe's" },
      experte: { lemma: "der Experte", pos: "noun", en: "expert" },
      fall: { lemma: "der Fall", pos: "noun", en: "case" },
      finanzielle: { lemma: "finanziell", pos: "adjective", en: "financial" },
      fordert: { lemma: "fordern", pos: "verb", en: "demands, calls for" },
      fragen: { lemma: "fragen", pos: "verb", en: "to ask" },
      geld: { lemma: "das Geld", pos: "noun", en: "money" },
      genug: { lemma: "genug", pos: "adverb", en: "enough" },
      genutzt: { lemma: "nutzen", pos: "verb", en: "used" },
      gerade: { lemma: "gerade", pos: "adverb", en: "right now, exactly" },
      gesammelt: { lemma: "sammeln", pos: "verb", en: "collected" },
      geschäftsmodelle: { lemma: "das Geschäftsmodell", pos: "noun", en: "business models" },
      gesehen: { lemma: "sehen", pos: "verb", en: "seen" },
      gilt: { lemma: "gelten", pos: "verb", en: "applies, holds true" },
      gleichzeitig: { lemma: "gleichzeitig", pos: "adverb", en: "at the same time" },
      globale: { lemma: "global", pos: "adjective", en: "global" },
      globaler: { lemma: "global", pos: "adjective", en: "global" },
      google: { lemma: "Google", pos: "noun (proper)", en: "Google" },
      große: { lemma: "groß", pos: "adjective", en: "large, big" },
      großen: { lemma: "groß", pos: "adjective", en: "large" },
      größten: { lemma: "groß", pos: "adjective", en: "largest" },
      haben: { lemma: "haben", pos: "verb", en: "to have" },
      handys: { lemma: "das Handy", pos: "noun", en: "mobile phones" },
      hat: { lemma: "haben", pos: "verb", en: "has" },
      hier: { lemma: "hier", pos: "adverb", en: "here" },
      hoch: { lemma: "hoch", pos: "adjective", en: "high" },
      hunderten: { lemma: "hundert", pos: "numeral", en: "hundreds" },
      ich: { lemma: "ich", pos: "pronoun", en: "I" },
      im: { lemma: "im (in dem)", pos: "preposition", en: "in the" },
      in: { lemma: "in", pos: "preposition", en: "in" },
      individuelle: { lemma: "individuell", pos: "adjective", en: "individual" },
      infrastruktur: { lemma: "die Infrastruktur", pos: "noun", en: "infrastructure" },
      infrastrukturen: { lemma: "die Infrastruktur", pos: "noun", en: "infrastructures" },
      installiert: { lemma: "installieren", pos: "verb", en: "installed" },
      ist: { lemma: "sein", pos: "verb", en: "is" },
      ja: { lemma: "ja", pos: "adverb", en: "yes" },
      jan: { lemma: "Jan", pos: "noun (proper)", en: "Jan (name)" },
      je: { lemma: "je", pos: "adverb", en: "ever" },
      jeweiligen: { lemma: "jeweilig", pos: "adjective", en: "respective, particular" },
      kalender: { lemma: "der Kalender", pos: "noun", en: "calendar" },
      ki: { lemma: "die KI", pos: "noun", en: "AI" },
      klicken: { lemma: "klicken", pos: "verb", en: "to click" },
      kommen: { lemma: "kommen", pos: "verb", en: "to come" },
      kommt: { lemma: "kommen", pos: "verb", en: "comes" },
      komplette: { lemma: "komplett", pos: "adjective", en: "complete, entire" },
      komplexe: { lemma: "komplex", pos: "adjective", en: "complex" },
      kontakte: { lemma: "der Kontakt", pos: "noun", en: "contacts" },
      kontrolle: { lemma: "die Kontrolle", pos: "noun", en: "control, oversight" },
      konzernen: { lemma: "der Konzern", pos: "noun", en: "corporations" },
      kostenlose: { lemma: "kostenlos", pos: "adjective", en: "free (of charge)" },
      können: { lemma: "können", pos: "verb", en: "can, to be able to" },
      leider: { lemma: "leider", pos: "adverb", en: "unfortunately" },
      lohnt: { lemma: "sich lohnen", pos: "verb", en: "is worth it" },
      mail: { lemma: "die Mail", pos: "noun", en: "mail" },
      maps: { lemma: "Maps", pos: "noun (proper)", en: "Maps" },
      mehr: { lemma: "mehr", pos: "adverb", en: "more" },
      mehrfach: { lemma: "mehrfach", pos: "adverb", en: "repeatedly, several times" },
      meine: { lemma: "mein", pos: "pronoun", en: "my" },
      meint: { lemma: "meinen", pos: "verb", en: "thinks, means" },
      mengen: { lemma: "die Menge", pos: "noun", en: "amounts, quantities" },
      menschen: { lemma: "der Mensch", pos: "noun", en: "people" },
      menschheit: { lemma: "die Menschheit", pos: "noun", en: "humanity, mankind" },
      messenger: { lemma: "der Messenger", pos: "noun", en: "messenger (app)" },
      meta: { lemma: "Meta", pos: "noun (proper)", en: "Meta" },
      mich: { lemma: "mich", pos: "pronoun", en: "me" },
      milliardenmarkt: { lemma: "der Milliardenmarkt", pos: "noun", en: "billion-euro market" },
      millionen: { lemma: "die Million", pos: "noun", en: "millions" },
      minutentakt: { lemma: "der Minutentakt", pos: "noun", en: "minute-by-minute intervals" },
      mit: { lemma: "mit", pos: "preposition", en: "with" },
      mut: { lemma: "der Mut", pos: "noun", en: "courage" },
      müssen: { lemma: "müssen", pos: "verb", en: "must, to have to" },
      nach: { lemma: "nach", pos: "preposition", en: "after, for, to" },
      nachts: { lemma: "nachts", pos: "adverb", en: "at night" },
      netzwerken: { lemma: "das Netzwerk", pos: "noun", en: "networks" },
      nicht: { lemma: "nicht", pos: "adverb", en: "not" },
      noch: { lemma: "noch", pos: "adverb", en: "still, yet" },
      nutzenden: { lemma: "der/die Nutzende", pos: "noun", en: "users" },
      nutzerprofile: { lemma: "das Nutzerprofil", pos: "noun", en: "user profiles" },
      nutzungsdaten: { lemma: "die Nutzungsdaten", pos: "noun (pl.)", en: "usage data" },
      ob: { lemma: "ob", pos: "conjunction", en: "whether" },
      oder: { lemma: "oder", pos: "conjunction", en: "or" },
      ortungsdaten: { lemma: "die Ortungsdaten", pos: "noun (pl.)", en: "location data" },
      penfrat: { lemma: "Penfrat", pos: "noun (proper)", en: "Penfrat (name)" },
      persönliche: { lemma: "persönlich", pos: "adjective", en: "personal" },
      persönlicher: { lemma: "persönlich", pos: "adjective", en: "personal" },
      plattformen: { lemma: "die Plattform", pos: "noun", en: "platforms" },
      politischen: { lemma: "politisch", pos: "adjective", en: "political" },
      produkt: { lemma: "das Produkt", pos: "noun", en: "product" },
      profile: { lemma: "das Profil", pos: "noun", en: "profiles" },
      ressourcen: { lemma: "die Ressource", pos: "noun", en: "resources" },
      riesiger: { lemma: "riesig", pos: "adjective", en: "huge, enormous" },
      rät: { lemma: "raten", pos: "verb", en: "advises" },
      schnell: { lemma: "schnell", pos: "adjective/adverb", en: "quick, quickly" },
      schwer: { lemma: "schwer", pos: "adjective", en: "difficult, hard" },
      seite: { lemma: "die Seite", pos: "noun", en: "side" },
      selbst: { lemma: "selbst", pos: "adverb/pronoun", en: "itself, even" },
      sich: { lemma: "sich", pos: "pronoun", en: "oneself" },
      sie: { lemma: "sie", pos: "pronoun", en: "they, she" },
      sind: { lemma: "sein", pos: "verb", en: "are" },
      so: { lemma: "so", pos: "adverb", en: "so, thus; (quoting) says" },
      sozialen: { lemma: "sozial", pos: "adjective", en: "social" },
      stehen: { lemma: "stehen", pos: "verb", en: "to stand, to be" },
      strenge: { lemma: "streng", pos: "adjective", en: "strict" },
      stärkere: { lemma: "stark", pos: "adjective", en: "stronger" },
      suche: { lemma: "die Suche", pos: "noun", en: "search" },
      tech: { lemma: "Tech", pos: "noun", en: "tech" },
      teilen: { lemma: "der Teil", pos: "noun", en: "parts (zu großen Teilen = to a large extent)" },
      telefon: { lemma: "das Telefon", pos: "noun", en: "telephone, phone" },
      telefons: { lemma: "das Telefon", pos: "noun", en: "phone's" },
      und: { lemma: "und", pos: "conjunction", en: "and" },
      unserer: { lemma: "unser", pos: "pronoun", en: "our" },
      unternehmen: { lemma: "das Unternehmen", pos: "noun", en: "company, companies" },
      us: { lemma: "US", pos: "adjective", en: "US" },
      verdienen: { lemma: "verdienen", pos: "verb", en: "to earn" },
      verdient: { lemma: "verdienen", pos: "verb", en: "is earned" },
      vergleichsweise: { lemma: "vergleichsweise", pos: "adverb", en: "comparatively" },
      viel: { lemma: "viel", pos: "adverb/adjective", en: "much, a lot" },
      viele: { lemma: "viele", pos: "pronoun", en: "many" },
      von: { lemma: "von", pos: "preposition", en: "of, from" },
      wenn: { lemma: "wenn", pos: "conjunction", en: "if, when" },
      werden: { lemma: "werden", pos: "verb", en: "to be (passive), will" },
      whatsapp: { lemma: "WhatsApp", pos: "noun (proper)", en: "WhatsApp" },
      wie: { lemma: "wie", pos: "conjunction/adverb", en: "like, as, how" },
      wir: { lemma: "wir", pos: "pronoun", en: "we" },
      wird: { lemma: "werden", pos: "verb", en: "is (being), will" },
      wirklich: { lemma: "wirklich", pos: "adverb", en: "really, truly" },
      wissen: { lemma: "wissen", pos: "verb", en: "to know" },
      wo: { lemma: "wo", pos: "adverb", en: "where" },
      womit: { lemma: "womit", pos: "adverb", en: "with what, whereby" },
      wurden: { lemma: "werden", pos: "verb", en: "were" },
      zu: { lemma: "zu", pos: "preposition", en: "to, too" },
      zugriff: { lemma: "der Zugriff", pos: "noun", en: "access" },
      zum: { lemma: "zum (zu dem)", pos: "preposition", en: "to the" },
      über: { lemma: "über", pos: "preposition", en: "over, about, via" },
      üblicherweise: { lemma: "üblicherweise", pos: "adverb", en: "usually" },
    },
    sentences: {
      "Apps sammeln große Mengen persönlicher Daten – aus denen Tech-Unternehmen Nutzerprofile erstellen und mit denen sie viel Geld verdienen können.":
        "Apps collect large amounts of personal data, from which tech companies create user profiles and with which they can earn a lot of money.",
      "Effektiver Datenschutz ist auch in der EU schwer durchzusetzen.":
        "Effective data protection is hard to enforce, even in the EU.",
      "Eine App wie ein Messenger ist schnell installiert.":
        "An app like a messenger is quickly installed.",
      "Bei der Abfrage, ob persönliche Daten genutzt werden dürfen, klicken viele einfach auf „Ja\" – und erlauben damit zum Beispiel WhatsApp, alle Kontakte des Telefons zu speichern.":
        "When asked whether personal data may be used, many simply click \"Yes\", thereby allowing WhatsApp, for example, to store all of the phone's contacts.",
      "Doch das ist noch nicht alles.":
        "But that is not all.",
      "Denn große Tech-Unternehmen kontrollieren komplette Infrastrukturen.":
        "Because large tech companies control entire infrastructures.",
      "Digitalexperte Jan Penfrat erklärt: Daten werden über das Telefon selbst, das Betriebssystem und die Apps gesammelt.":
        "Digital expert Jan Penfrat explains: data is collected via the phone itself, the operating system and the apps.",
      "Bei Google sind das zum Beispiel Google-Mail, Kontakte, Kalender – und Google Maps, „wo die Aufenthaltsorte der Menschen im Minutentakt mit aufgezeichnet werden können.\"":
        "At Google, that includes, for example, Google Mail, contacts, calendar, and Google Maps, \"where people's whereabouts can be recorded minute by minute.\"",
      "Dazu kommen Annahmen der Unternehmen selbst.":
        "On top of that come the companies' own assumptions.",
      "„Wenn sie also Zugriff haben auf meine Ortungsdaten und wissen, wo ich mich üblicherweise nachts aufhalte, können sie davon ausgehen: Das ist meine Wohnadresse\", erklärt Penfrat.":
        "\"So if they have access to my location data and know where I usually spend the night, they can assume: that is my home address\", explains Penfrat.",
      "Aus den Nutzungsdaten und den Annahmen können individuelle Profile erstellt werden.":
        "From the usage data and the assumptions, individual profiles can be created.",
      "„Das ist ein riesiger, globaler Milliardenmarkt, auf dem persönliche Datenprofile von Menschen einfach verhökert werden,\" so Penfrat.":
        "\"This is a huge, global billion-euro market on which people's personal data profiles are simply sold off\", says Penfrat.",
      "Dabei hat die EU vergleichsweise strenge Datenschutzregeln.":
        "In fact, the EU has comparatively strict data protection rules.",
      "Mehrfach wurden Konzerne wie Apple, Meta oder Google zu Strafen von Hunderten Millionen Euro verurteilt.":
        "Several times, corporations like Apple, Meta or Google have been sentenced to fines of hundreds of millions of euros.",
      "Doch das ist nicht hoch genug, meint Penfrat.":
        "But that is not high enough, Penfrat thinks.",
      "Und eine wirklich effektive Kontrolle durch die EU ist nicht einfach: Die Tech-Konzerne besitzen globale Infrastrukturen, große finanzielle Ressourcen und komplexe Geschäftsmodelle.":
        "And really effective oversight by the EU is not easy: the tech corporations own global infrastructures, large financial resources and complex business models.",
      "Dazu kommt Europas Abhängigkeit: Cloud-Dienste, Betriebssysteme, Plattformen und KI-Infrastruktur kommen zu großen Teilen von US-Unternehmen.":
        "On top of that comes Europe's dependence: cloud services, operating systems, platforms and AI infrastructure come to a large extent from US companies.",
      "Nutzenden rät Penfrat, sich zu fragen, womit im jeweiligen Fall gerade Geld verdient wird.":
        "Penfrat advises users to ask themselves what exactly money is being made from in each case.",
      "Es gilt: „Wenn ich nicht bezahle, dann bin ich das Produkt.\" Kostenlose Dienste werden also mit Daten bezahlt.":
        "It holds true: \"If I don't pay, then I am the product.\" Free services are therefore paid for with data.",
      "Daher lohnt sich die Suche nach Alternativen – wie nach entsprechenden Handys oder sozialen Netzwerken, so der Experte.":
        "So it is worth searching for alternatives, such as suitable phones or social networks, says the expert.",
      "Gleichzeitig fordert Penfrat stärkere Regulierungen und mehr politischen Mut.":
        "At the same time, Penfrat calls for stronger regulation and more political courage.",
      "„Denn wir müssen es hier aufnehmen mit den größten und mächtigsten Konzernen, die die Menschheit je gesehen hat – und die stehen leider nicht auf unserer Seite.\"":
        "\"Because here we have to take on the biggest and most powerful corporations that humanity has ever seen, and unfortunately they are not on our side.\"",
    },
  },
  {
    id: "bauernhof",
    category: "Gesundheit",
    level: "B2",
    photo: "https://picsum.photos/seed/bauernhof/600/400",
    title: "Warum eine Kindheit auf dem Bauernhof gesund ist",
    desc: "Wie Mikroorganismen das Immunsystem von Landkindern schützen.",
    paragraphs: [
      `In der Forschung untersucht man seit Jahren Kinder, die auf dem Land groß werden. Dabei hat man festgestellt: Sie haben bestimmte Krankheiten seltener als Stadtkinder. Dabei spielen Mikroorganismen eine wichtige Rolle.`,
      `Zwischen Feldern, Wiesen und Kühen groß zu werden – das stellen sich viele sehr schön vor. Darüber hinaus ist eine Kindheit auf dem Bauernhof aber auch gut für die Gesundheit. Seit 1989 gibt es in der Forschung die „Hygiene-Hypothese": Kinder, die zu wenig mit Keimen in Kontakt kommen, entwickeln später häufiger Heuschnupfen, Asthma oder Neurodermitis – anders als Kinder, die zum Beispiel durch einen Kuhstall vielen Bakterien ausgesetzt sind.`,
      `Früher dachte man: Je mehr Kontakt Kinder mit Keimen haben, desto besser ist das für ihr Immunsystem. Doch so einfach ist das nicht, wie ein internationales Forschungsteam rund um den Epidemiologen Markus Ege herausgefunden hat. Man hat sich dafür die Untersuchungsergebnisse von über 1000 Grundschulkindern aus Europa angesehen. Die Forschenden untersuchten auch den Staub, der in den Wohnungen und Ställen lag.`,
      `Das Ergebnis: Entscheidend für die schützende Wirkung ist nicht die Menge, sondern die Art der Mikroorganismen – und vor allem ihre Stoffwechselprodukte. Wenn diese eingeatmet werden, hemmen sie bestimmte Entzündungsprozesse im Körper. Das findet bereits in den ersten Lebensjahren statt, so Ege. Die Daten der Grundschulkinder zeigen das. Das Immunsystem eines Kindes profitiert möglicherweise bereits dann, wenn sich seine Mutter vor der Geburt regelmäßig auf einem Bauernhof aufhält.`,
      `Die wichtigste Botschaft des Forschungsteams ist aber: Nicht der Bauernhof an sich ist wichtig, sondern bestimmte Mikroorganismen, die dort vorkommen. Studienleiter Ege sagt: Langfristig will man ihren Schutz medizinisch nachbilden. Daraus könnten dann irgendwann bessere Behandlungsmöglichkeiten für Asthma, Heuschnupfen und Neurodermitis entstehen – „aber eben nicht bald", erklärt Ege.`,
    ],
    glossary: {
      kindheit: { lemma: "die Kindheit", pos: "noun", en: "childhood" },
      bauernhof: { lemma: "der Bauernhof", pos: "noun", en: "farm" },
      gesund: { lemma: "gesund", pos: "adjective", en: "healthy" },
      forschung: { lemma: "die Forschung", pos: "noun", en: "research" },
      untersucht: { lemma: "untersuchen", pos: "verb", en: "to study, to examine" },
      krankheiten: { lemma: "die Krankheit", pos: "noun", en: "diseases" },
      seltener: { lemma: "selten", pos: "adverb", en: "less often" },
      mikroorganismen: { lemma: "der Mikroorganismus", pos: "noun", en: "microorganisms" },
      gesundheit: { lemma: "die Gesundheit", pos: "noun", en: "health" },
      keimen: { lemma: "der Keim", pos: "noun", en: "germs" },
      heuschnupfen: { lemma: "der Heuschnupfen", pos: "noun", en: "hay fever" },
      bakterien: { lemma: "die Bakterien", pos: "noun (pl.)", en: "bacteria" },
      immunsystem: { lemma: "das Immunsystem", pos: "noun", en: "immune system" },
      staub: { lemma: "der Staub", pos: "noun", en: "dust" },
      schützende: { lemma: "schützend", pos: "adjective", en: "protective" },
      wirkung: { lemma: "die Wirkung", pos: "noun", en: "effect" },
      eingeatmet: { lemma: "einatmen", pos: "verb", en: "to inhale" },
      hemmen: { lemma: "hemmen", pos: "verb", en: "to inhibit" },
      geburt: { lemma: "die Geburt", pos: "noun", en: "birth" },
      behandlungsmöglichkeiten: { lemma: "die Behandlungsmöglichkeit", pos: "noun", en: "treatment options" },
    },
    words: {
      "1000": { lemma: "1000", pos: "numeral", en: "1,000" },
      "1989": { lemma: "1989", pos: "numeral", en: "1989 (year)" },
      aber: { lemma: "aber", pos: "conjunction", en: "but" },
      allem: { lemma: "all", pos: "pronoun", en: "all (vor allem = above all)" },
      als: { lemma: "als", pos: "conjunction", en: "than, as, when" },
      an: { lemma: "an", pos: "preposition", en: "at, on" },
      anders: { lemma: "anders", pos: "adverb", en: "differently, unlike" },
      angesehen: { lemma: "ansehen", pos: "verb", en: "looked at, reviewed" },
      art: { lemma: "die Art", pos: "noun", en: "type, kind" },
      asthma: { lemma: "das Asthma", pos: "noun", en: "asthma" },
      auch: { lemma: "auch", pos: "adverb", en: "also, too" },
      auf: { lemma: "auf", pos: "preposition", en: "on, to" },
      aufhält: { lemma: "sich aufhalten", pos: "verb", en: "stays, spends time" },
      aus: { lemma: "aus", pos: "preposition", en: "from, out of" },
      ausgesetzt: { lemma: "aussetzen", pos: "verb", en: "exposed (to)" },
      bakterien: { lemma: "die Bakterien", pos: "noun (pl.)", en: "bacteria" },
      bald: { lemma: "bald", pos: "adverb", en: "soon" },
      bauernhof: { lemma: "der Bauernhof", pos: "noun", en: "farm" },
      beispiel: { lemma: "das Beispiel", pos: "noun", en: "example" },
      bereits: { lemma: "bereits", pos: "adverb", en: "already" },
      besser: { lemma: "besser", pos: "adjective", en: "better" },
      bessere: { lemma: "besser", pos: "adjective", en: "better" },
      bestimmte: { lemma: "bestimmt", pos: "adjective", en: "certain, particular" },
      botschaft: { lemma: "die Botschaft", pos: "noun", en: "message" },
      dabei: { lemma: "dabei", pos: "adverb", en: "in doing so, here" },
      dachte: { lemma: "denken", pos: "verb", en: "thought" },
      dafür: { lemma: "dafür", pos: "adverb", en: "for this" },
      dann: { lemma: "dann", pos: "adverb", en: "then" },
      daraus: { lemma: "daraus", pos: "adverb", en: "from this, out of it" },
      darüber: { lemma: "darüber", pos: "adverb", en: "about it (darüber hinaus = moreover)" },
      das: { lemma: "das", pos: "article/pronoun", en: "the, that" },
      daten: { lemma: "die Daten", pos: "noun (pl.)", en: "data" },
      dem: { lemma: "dem", pos: "article", en: "the (dative)" },
      den: { lemma: "den", pos: "article", en: "the" },
      der: { lemma: "der", pos: "article", en: "the" },
      des: { lemma: "des", pos: "article", en: "of the" },
      desto: { lemma: "desto", pos: "conjunction", en: "the (je … desto = the … the)" },
      die: { lemma: "die", pos: "article", en: "the" },
      diese: { lemma: "diese", pos: "pronoun", en: "this, these" },
      doch: { lemma: "doch", pos: "adverb", en: "but, however" },
      dort: { lemma: "dort", pos: "adverb", en: "there" },
      durch: { lemma: "durch", pos: "preposition", en: "through, by" },
      eben: { lemma: "eben", pos: "adverb", en: "just, precisely" },
      ege: { lemma: "Ege", pos: "noun (proper)", en: "Ege (name)" },
      ein: { lemma: "ein", pos: "article", en: "a, an" },
      eine: { lemma: "eine", pos: "article", en: "a, an" },
      einem: { lemma: "einem", pos: "article", en: "a (dative)" },
      einen: { lemma: "einen", pos: "article", en: "a (accusative)" },
      eines: { lemma: "eines", pos: "article", en: "of a" },
      einfach: { lemma: "einfach", pos: "adjective/adverb", en: "simple, simply" },
      eingeatmet: { lemma: "einatmen", pos: "verb", en: "inhaled" },
      entscheidend: { lemma: "entscheidend", pos: "adjective", en: "decisive, crucial" },
      entstehen: { lemma: "entstehen", pos: "verb", en: "to arise, to emerge" },
      entwickeln: { lemma: "entwickeln", pos: "verb", en: "to develop" },
      entzündungsprozesse: { lemma: "der Entzündungsprozess", pos: "noun", en: "inflammatory processes" },
      epidemiologen: { lemma: "der Epidemiologe", pos: "noun", en: "epidemiologist" },
      ergebnis: { lemma: "das Ergebnis", pos: "noun", en: "result" },
      erklärt: { lemma: "erklären", pos: "verb", en: "explains" },
      ersten: { lemma: "erste", pos: "adjective", en: "first" },
      es: { lemma: "es", pos: "pronoun", en: "it" },
      europa: { lemma: "Europa", pos: "noun (proper)", en: "Europe" },
      feldern: { lemma: "das Feld", pos: "noun", en: "fields" },
      festgestellt: { lemma: "feststellen", pos: "verb", en: "found, established" },
      findet: { lemma: "stattfinden", pos: "verb", en: "takes place (findet statt)" },
      forschenden: { lemma: "die Forschenden", pos: "noun", en: "researchers" },
      forschung: { lemma: "die Forschung", pos: "noun", en: "research" },
      forschungsteam: { lemma: "das Forschungsteam", pos: "noun", en: "research team" },
      forschungsteams: { lemma: "das Forschungsteam", pos: "noun", en: "research team's" },
      früher: { lemma: "früher", pos: "adverb", en: "earlier, in the past" },
      für: { lemma: "für", pos: "preposition", en: "for" },
      geburt: { lemma: "die Geburt", pos: "noun", en: "birth" },
      gesundheit: { lemma: "die Gesundheit", pos: "noun", en: "health" },
      gibt: { lemma: "geben (es gibt)", pos: "verb", en: "there is/are" },
      groß: { lemma: "groß", pos: "adjective", en: "big (groß werden = to grow up)" },
      grundschulkinder: { lemma: "das Grundschulkind", pos: "noun", en: "primary-school children" },
      grundschulkindern: { lemma: "das Grundschulkind", pos: "noun", en: "primary-school children (dative)" },
      gut: { lemma: "gut", pos: "adjective", en: "good" },
      haben: { lemma: "haben", pos: "verb", en: "to have" },
      hat: { lemma: "haben", pos: "verb", en: "has" },
      hemmen: { lemma: "hemmen", pos: "verb", en: "to inhibit" },
      herausgefunden: { lemma: "herausfinden", pos: "verb", en: "found out" },
      heuschnupfen: { lemma: "der Heuschnupfen", pos: "noun", en: "hay fever" },
      hinaus: { lemma: "hinaus", pos: "adverb", en: "beyond (darüber hinaus = moreover)" },
      hygiene: { lemma: "die Hygiene", pos: "noun", en: "hygiene" },
      hypothese: { lemma: "die Hypothese", pos: "noun", en: "hypothesis" },
      häufiger: { lemma: "häufig", pos: "adverb", en: "more often" },
      ihr: { lemma: "ihr", pos: "pronoun", en: "their, her" },
      ihre: { lemma: "ihre", pos: "pronoun", en: "their, her" },
      ihren: { lemma: "ihren", pos: "pronoun", en: "their, her" },
      im: { lemma: "im (in dem)", pos: "preposition", en: "in the" },
      immunsystem: { lemma: "das Immunsystem", pos: "noun", en: "immune system" },
      in: { lemma: "in", pos: "preposition", en: "in" },
      internationales: { lemma: "international", pos: "adjective", en: "international" },
      irgendwann: { lemma: "irgendwann", pos: "adverb", en: "at some point, someday" },
      ist: { lemma: "sein", pos: "verb", en: "is" },
      jahren: { lemma: "das Jahr", pos: "noun", en: "years" },
      je: { lemma: "je", pos: "adverb", en: "the (je … desto), ever" },
      keimen: { lemma: "der Keim", pos: "noun", en: "germs" },
      kinder: { lemma: "das Kind", pos: "noun", en: "children" },
      kindes: { lemma: "das Kind", pos: "noun", en: "child's" },
      kindheit: { lemma: "die Kindheit", pos: "noun", en: "childhood" },
      kommen: { lemma: "kommen", pos: "verb", en: "to come" },
      kontakt: { lemma: "der Kontakt", pos: "noun", en: "contact" },
      krankheiten: { lemma: "die Krankheit", pos: "noun", en: "diseases" },
      kuhstall: { lemma: "der Kuhstall", pos: "noun", en: "cowshed" },
      könnten: { lemma: "können", pos: "verb", en: "could" },
      körper: { lemma: "der Körper", pos: "noun", en: "body" },
      kühen: { lemma: "die Kuh", pos: "noun", en: "cows" },
      lag: { lemma: "liegen", pos: "verb", en: "lay, was" },
      land: { lemma: "das Land", pos: "noun", en: "countryside, country" },
      langfristig: { lemma: "langfristig", pos: "adverb", en: "in the long term" },
      lebensjahren: { lemma: "das Lebensjahr", pos: "noun", en: "years of life" },
      man: { lemma: "man", pos: "pronoun", en: "one, you (impersonal)" },
      markus: { lemma: "Markus", pos: "noun (proper)", en: "Markus (name)" },
      medizinisch: { lemma: "medizinisch", pos: "adjective", en: "medically" },
      mehr: { lemma: "mehr", pos: "adverb", en: "more" },
      menge: { lemma: "die Menge", pos: "noun", en: "amount, quantity" },
      mikroorganismen: { lemma: "der Mikroorganismus", pos: "noun", en: "microorganisms" },
      mit: { lemma: "mit", pos: "preposition", en: "with" },
      mutter: { lemma: "die Mutter", pos: "noun", en: "mother" },
      möglicherweise: { lemma: "möglicherweise", pos: "adverb", en: "possibly" },
      nachbilden: { lemma: "nachbilden", pos: "verb", en: "to replicate, to reproduce" },
      neurodermitis: { lemma: "die Neurodermitis", pos: "noun", en: "atopic dermatitis, eczema" },
      nicht: { lemma: "nicht", pos: "adverb", en: "not" },
      oder: { lemma: "oder", pos: "conjunction", en: "or" },
      profitiert: { lemma: "profitieren", pos: "verb", en: "benefits" },
      regelmäßig: { lemma: "regelmäßig", pos: "adverb", en: "regularly" },
      rolle: { lemma: "die Rolle", pos: "noun", en: "role" },
      rund: { lemma: "rund (um)", pos: "adverb", en: "around (rund um = around)" },
      sagt: { lemma: "sagen", pos: "verb", en: "says" },
      schutz: { lemma: "der Schutz", pos: "noun", en: "protection" },
      schön: { lemma: "schön", pos: "adjective", en: "nice, lovely" },
      schützende: { lemma: "schützend", pos: "adjective", en: "protective" },
      sehr: { lemma: "sehr", pos: "adverb", en: "very" },
      seine: { lemma: "sein", pos: "pronoun", en: "his, its" },
      seit: { lemma: "seit", pos: "preposition", en: "since, for" },
      seltener: { lemma: "selten", pos: "adverb", en: "less often" },
      sich: { lemma: "sich", pos: "pronoun", en: "oneself" },
      sie: { lemma: "sie", pos: "pronoun", en: "they, she" },
      sind: { lemma: "sein", pos: "verb", en: "are" },
      so: { lemma: "so", pos: "adverb", en: "so, thus" },
      sondern: { lemma: "sondern", pos: "conjunction", en: "but (rather)" },
      spielen: { lemma: "spielen", pos: "verb", en: "to play" },
      später: { lemma: "später", pos: "adverb", en: "later" },
      stadtkinder: { lemma: "das Stadtkind", pos: "noun", en: "city children" },
      statt: { lemma: "stattfinden", pos: "verb", en: "(findet) statt = takes place" },
      staub: { lemma: "der Staub", pos: "noun", en: "dust" },
      stellen: { lemma: "sich vorstellen", pos: "verb", en: "imagine (stellen … vor)" },
      stoffwechselprodukte: { lemma: "das Stoffwechselprodukt", pos: "noun", en: "metabolic products" },
      studienleiter: { lemma: "der Studienleiter", pos: "noun", en: "study director" },
      ställen: { lemma: "der Stall", pos: "noun", en: "stables, barns" },
      um: { lemma: "um", pos: "preposition", en: "around (rund um)" },
      und: { lemma: "und", pos: "conjunction", en: "and" },
      untersucht: { lemma: "untersuchen", pos: "verb", en: "studies, examines" },
      untersuchten: { lemma: "untersuchen", pos: "verb", en: "studied, examined" },
      untersuchungsergebnisse: { lemma: "das Untersuchungsergebnis", pos: "noun", en: "examination results" },
      viele: { lemma: "viele", pos: "pronoun", en: "many" },
      vielen: { lemma: "viele", pos: "pronoun", en: "many (dative)" },
      von: { lemma: "von", pos: "preposition", en: "of, from" },
      vor: { lemma: "vor", pos: "preposition", en: "before (sich … vorstellen = to imagine)" },
      vorkommen: { lemma: "vorkommen", pos: "verb", en: "to occur, to be present" },
      wenig: { lemma: "wenig", pos: "adverb", en: "little, few" },
      wenn: { lemma: "wenn", pos: "conjunction", en: "if, when" },
      werden: { lemma: "werden", pos: "verb", en: "to become, to be (passive)" },
      wichtig: { lemma: "wichtig", pos: "adjective", en: "important" },
      wichtige: { lemma: "wichtig", pos: "adjective", en: "important" },
      wichtigste: { lemma: "wichtig", pos: "adjective", en: "most important" },
      wie: { lemma: "wie", pos: "conjunction/adverb", en: "like, as, how" },
      wiesen: { lemma: "die Wiese", pos: "noun", en: "meadows" },
      will: { lemma: "wollen", pos: "verb", en: "wants to" },
      wirkung: { lemma: "die Wirkung", pos: "noun", en: "effect" },
      wohnungen: { lemma: "die Wohnung", pos: "noun", en: "flats, homes" },
      zeigen: { lemma: "zeigen", pos: "verb", en: "to show" },
      zu: { lemma: "zu", pos: "preposition", en: "to, too" },
      zum: { lemma: "zum (zu dem)", pos: "preposition", en: "to the" },
      zwischen: { lemma: "zwischen", pos: "preposition", en: "between" },
      über: { lemma: "über", pos: "preposition", en: "over, more than, about" },
    },
    sentences: {
      "In der Forschung untersucht man seit Jahren Kinder, die auf dem Land groß werden.":
        "In research, children who grow up in the countryside have been studied for years.",
      "Dabei hat man festgestellt: Sie haben bestimmte Krankheiten seltener als Stadtkinder.":
        "In doing so, it was found: they suffer from certain diseases less often than city children.",
      "Dabei spielen Mikroorganismen eine wichtige Rolle.":
        "Microorganisms play an important role in this.",
      "Zwischen Feldern, Wiesen und Kühen groß zu werden – das stellen sich viele sehr schön vor.":
        "Growing up among fields, meadows and cows, many people picture that as very lovely.",
      "Darüber hinaus ist eine Kindheit auf dem Bauernhof aber auch gut für die Gesundheit.":
        "Beyond that, however, a childhood on a farm is also good for one's health.",
      "Seit 1989 gibt es in der Forschung die „Hygiene-Hypothese\": Kinder, die zu wenig mit Keimen in Kontakt kommen, entwickeln später häufiger Heuschnupfen, Asthma oder Neurodermitis – anders als Kinder, die zum Beispiel durch einen Kuhstall vielen Bakterien ausgesetzt sind.":
        "Since 1989 there has been the \"hygiene hypothesis\" in research: children who come into contact with too few germs later develop hay fever, asthma or eczema more often, unlike children who are exposed to many bacteria, for example through a cowshed.",
      "Früher dachte man: Je mehr Kontakt Kinder mit Keimen haben, desto besser ist das für ihr Immunsystem.":
        "In the past, people thought: the more contact children have with germs, the better it is for their immune system.",
      "Doch so einfach ist das nicht, wie ein internationales Forschungsteam rund um den Epidemiologen Markus Ege herausgefunden hat.":
        "But it is not that simple, as an international research team led by the epidemiologist Markus Ege has found out.",
      "Man hat sich dafür die Untersuchungsergebnisse von über 1000 Grundschulkindern aus Europa angesehen.":
        "For this, the examination results of over 1,000 primary-school children from Europe were reviewed.",
      "Die Forschenden untersuchten auch den Staub, der in den Wohnungen und Ställen lag.":
        "The researchers also examined the dust that lay in the homes and stables.",
      "Das Ergebnis: Entscheidend für die schützende Wirkung ist nicht die Menge, sondern die Art der Mikroorganismen – und vor allem ihre Stoffwechselprodukte.":
        "The result: what is decisive for the protective effect is not the quantity but the type of microorganisms, and above all their metabolic products.",
      "Wenn diese eingeatmet werden, hemmen sie bestimmte Entzündungsprozesse im Körper.":
        "When these are inhaled, they inhibit certain inflammatory processes in the body.",
      "Das findet bereits in den ersten Lebensjahren statt, so Ege.":
        "This already takes place in the first years of life, according to Ege.",
      "Die Daten der Grundschulkinder zeigen das.":
        "The data from the primary-school children show this.",
      "Das Immunsystem eines Kindes profitiert möglicherweise bereits dann, wenn sich seine Mutter vor der Geburt regelmäßig auf einem Bauernhof aufhält.":
        "A child's immune system possibly benefits as early as when its mother regularly stays on a farm before the birth.",
      "Die wichtigste Botschaft des Forschungsteams ist aber: Nicht der Bauernhof an sich ist wichtig, sondern bestimmte Mikroorganismen, die dort vorkommen.":
        "The research team's most important message, however, is: it is not the farm itself that matters, but certain microorganisms that occur there.",
      "Studienleiter Ege sagt: Langfristig will man ihren Schutz medizinisch nachbilden.":
        "Study director Ege says: in the long term, they want to replicate their protection medically.",
      "Daraus könnten dann irgendwann bessere Behandlungsmöglichkeiten für Asthma, Heuschnupfen und Neurodermitis entstehen – „aber eben nicht bald\", erklärt Ege.":
        "From that, better treatment options for asthma, hay fever and eczema could one day emerge, \"but not soon\", Ege explains.",
    },
  },
  {
    id: "schule",
    category: "Bildung",
    level: "B2",
    photo: "https://picsum.photos/seed/schule/600/400",
    title: "Eine Schule, die Chancen bietet",
    desc: "Eine Bonner Grundschule kämpft gegen ungleiche Bildungschancen.",
    paragraphs: [
      `Wie gut ein Kind in der Schule ist und welchen Abschluss es macht, hängt in Deutschland immer noch stark von der sozialen Herkunft ab. Eine Grundschule in Bonn zeigt, dass man daran etwas ändern kann.`,
      `Im Vergleich zu anderen Ländern hängt in Deutschland der Bildungserfolg immer noch stark von der sozialen Herkunft, den finanziellen Möglichkeiten und der Bildung der Familien ab. Der Nationale Bildungsbericht 2026 zeigt, dass diese Ungleichheit bereits in den ersten Lebensjahren entsteht und dann den weiteren Bildungsweg von Kindern beeinflusst. Was kann man gegen die fehlende Chancengerechtigkeit tun?`,
      `Fast alle 250 Schülerinnen und Schüler der Bonner Kettelerschule haben eine Zuwanderungsgeschichte, viele sprechen zu Hause kein Deutsch und jedes dritte Kind muss besonders gefördert werden. Trotzdem lag die Schule in den letzten Jahren bei Leistungstests im Bundesland NRW über dem Durchschnitt. „Ich will, dass unsere Kinder hier alles lernen können, damit sie später genauso gute Chancen haben wie Kinder aus Elternhäusern, in denen Kindern von Anfang an sehr viel ermöglicht wird", sagt Schulleiterin Christina Lang-Winter, die 2004 als junge Lehrerin an die Schule kam.`,
      `In der Kettelerschule lernen die Kinder in sogenannten „Lernfamilien". Das bedeutet, dass Jahrgänge zusammen unterrichtet werden und sich so Sechs- und Neunjährige gegenseitig unterstützen. Außerdem arbeitet an der Grundschule ein Team aus Lehrerinnen und Lehrern sowie Sozial- und Sonderpädagogen eng zusammen und fördert die Kinder individuell. Vor allem in den ersten Klassen hat das Lesen einen besonderen Stellenwert – und Sprache im Allgemeinen: „Wenn ich keine Sprache habe, kann ich auch nicht gebildet werden", so Lang-Winter.`,
      `Die Sprachförderung beginnt bei ihr aber schon vor der Einschulung. Dafür ist die Schule mit umliegenden Kitas im regelmäßigen Austausch: Schulkinder lesen in der Kita vor, und die Vorschulkinder aus der Kita kommen zweimal pro Woche in die Grundschule. So lernt man die Kinder schon vorher kennen und kann sie frühestmöglich unterstützen, erklärt die Schulleiterin. Mit Erfolg: Heute bekommen 30 Prozent ihrer Schülerinnen und Schüler eine Gymnasialempfehlung, 2007 waren es nur 0,5 Prozent.`,
    ],
    glossary: {
      schule: { lemma: "die Schule", pos: "noun", en: "school" },
      chancen: { lemma: "die Chance", pos: "noun", en: "opportunities" },
      abschluss: { lemma: "der Abschluss", pos: "noun", en: "diploma, degree" },
      herkunft: { lemma: "die Herkunft", pos: "noun", en: "origin, background" },
      grundschule: { lemma: "die Grundschule", pos: "noun", en: "primary school" },
      bildung: { lemma: "die Bildung", pos: "noun", en: "education" },
      ungleichheit: { lemma: "die Ungleichheit", pos: "noun", en: "inequality" },
      entsteht: { lemma: "entstehen", pos: "verb", en: "to arise, to emerge" },
      beeinflusst: { lemma: "beeinflussen", pos: "verb", en: "to influence" },
      gefördert: { lemma: "fördern", pos: "verb", en: "to support, to promote" },
      durchschnitt: { lemma: "der Durchschnitt", pos: "noun", en: "average" },
      schulleiterin: { lemma: "die Schulleiterin", pos: "noun", en: "headmistress" },
      jahrgänge: { lemma: "der Jahrgang", pos: "noun", en: "year groups" },
      unterrichtet: { lemma: "unterrichten", pos: "verb", en: "to teach" },
      unterstützen: { lemma: "unterstützen", pos: "verb", en: "to support" },
      lesen: { lemma: "lesen", pos: "verb", en: "to read" },
      sprachförderung: { lemma: "die Sprachförderung", pos: "noun", en: "language support" },
      einschulung: { lemma: "die Einschulung", pos: "noun", en: "school enrollment" },
      austausch: { lemma: "der Austausch", pos: "noun", en: "exchange" },
    },
    words: {
      "0": { lemma: "0", pos: "numeral", en: "0 (in 0,5 = 0.5)" },
      "2004": { lemma: "2004", pos: "numeral", en: "2004 (year)" },
      "2007": { lemma: "2007", pos: "numeral", en: "2007 (year)" },
      "2026": { lemma: "2026", pos: "numeral", en: "2026 (year)" },
      "250": { lemma: "250", pos: "numeral", en: "250" },
      "30": { lemma: "30", pos: "numeral", en: "30" },
      "5": { lemma: "5", pos: "numeral", en: "5 (in 0,5 = 0.5)" },
      ab: { lemma: "abhängen (von)", pos: "verb", en: "(hängt … ab = depends on)" },
      aber: { lemma: "aber", pos: "conjunction", en: "but" },
      abschluss: { lemma: "der Abschluss", pos: "noun", en: "diploma, degree" },
      alle: { lemma: "alle", pos: "pronoun", en: "all" },
      allem: { lemma: "all", pos: "pronoun", en: "all (vor allem = above all)" },
      alles: { lemma: "alles", pos: "pronoun", en: "everything" },
      allgemeinen: { lemma: "allgemein", pos: "adjective", en: "general (im Allgemeinen = in general)" },
      als: { lemma: "als", pos: "conjunction", en: "as, than, when" },
      an: { lemma: "an", pos: "preposition", en: "at, on, to" },
      anderen: { lemma: "andere", pos: "adjective", en: "other" },
      anfang: { lemma: "der Anfang", pos: "noun", en: "beginning (von Anfang an = from the start)" },
      arbeitet: { lemma: "arbeiten", pos: "verb", en: "works" },
      auch: { lemma: "auch", pos: "adverb", en: "also, too" },
      aus: { lemma: "aus", pos: "preposition", en: "from, out of" },
      austausch: { lemma: "der Austausch", pos: "noun", en: "exchange" },
      außerdem: { lemma: "außerdem", pos: "adverb", en: "besides, in addition" },
      bedeutet: { lemma: "bedeuten", pos: "verb", en: "means" },
      beeinflusst: { lemma: "beeinflussen", pos: "verb", en: "influences" },
      beginnt: { lemma: "beginnen", pos: "verb", en: "begins" },
      bei: { lemma: "bei", pos: "preposition", en: "at, with" },
      bekommen: { lemma: "bekommen", pos: "verb", en: "receive, get" },
      bereits: { lemma: "bereits", pos: "adverb", en: "already" },
      besonderen: { lemma: "besondere", pos: "adjective", en: "special, particular" },
      besonders: { lemma: "besonders", pos: "adverb", en: "especially" },
      bildung: { lemma: "die Bildung", pos: "noun", en: "education" },
      bildungsbericht: { lemma: "der Bildungsbericht", pos: "noun", en: "education report" },
      bildungserfolg: { lemma: "der Bildungserfolg", pos: "noun", en: "educational success" },
      bildungsweg: { lemma: "der Bildungsweg", pos: "noun", en: "educational path" },
      bonn: { lemma: "Bonn", pos: "noun (proper)", en: "Bonn (city)" },
      bonner: { lemma: "Bonner", pos: "adjective", en: "of Bonn" },
      bundesland: { lemma: "das Bundesland", pos: "noun", en: "federal state" },
      chancen: { lemma: "die Chance", pos: "noun", en: "opportunities" },
      chancengerechtigkeit: { lemma: "die Chancengerechtigkeit", pos: "noun", en: "equality of opportunity" },
      christina: { lemma: "Christina", pos: "noun (proper)", en: "Christina (name)" },
      dafür: { lemma: "dafür", pos: "adverb", en: "for this" },
      damit: { lemma: "damit", pos: "conjunction", en: "so that" },
      dann: { lemma: "dann", pos: "adverb", en: "then" },
      daran: { lemma: "daran", pos: "adverb", en: "about it, on it" },
      das: { lemma: "das", pos: "article/pronoun", en: "the, that" },
      dass: { lemma: "dass", pos: "conjunction", en: "that" },
      dem: { lemma: "dem", pos: "article", en: "the (dative)" },
      den: { lemma: "den", pos: "article", en: "the" },
      denen: { lemma: "denen", pos: "pronoun", en: "which, whom (in denen = in which)" },
      der: { lemma: "der", pos: "article", en: "the" },
      deutsch: { lemma: "Deutsch", pos: "noun", en: "German (language)" },
      deutschland: { lemma: "Deutschland", pos: "noun (proper)", en: "Germany" },
      die: { lemma: "die", pos: "article", en: "the" },
      diese: { lemma: "diese", pos: "pronoun", en: "this, these" },
      dritte: { lemma: "dritte", pos: "adjective", en: "third (jedes dritte = every third)" },
      durchschnitt: { lemma: "der Durchschnitt", pos: "noun", en: "average" },
      ein: { lemma: "ein", pos: "article", en: "a, an" },
      eine: { lemma: "eine", pos: "article", en: "a, an" },
      einen: { lemma: "einen", pos: "article", en: "a (accusative)" },
      einschulung: { lemma: "die Einschulung", pos: "noun", en: "school enrollment" },
      elternhäusern: { lemma: "das Elternhaus", pos: "noun", en: "parental homes" },
      eng: { lemma: "eng", pos: "adjective/adverb", en: "closely" },
      entsteht: { lemma: "entstehen", pos: "verb", en: "arises, emerges" },
      erfolg: { lemma: "der Erfolg", pos: "noun", en: "success" },
      erklärt: { lemma: "erklären", pos: "verb", en: "explains" },
      ermöglicht: { lemma: "ermöglichen", pos: "verb", en: "made possible, enabled" },
      ersten: { lemma: "erste", pos: "adjective", en: "first" },
      es: { lemma: "es", pos: "pronoun", en: "it" },
      etwas: { lemma: "etwas", pos: "pronoun", en: "something" },
      familien: { lemma: "die Familie", pos: "noun", en: "families" },
      fast: { lemma: "fast", pos: "adverb", en: "almost" },
      fehlende: { lemma: "fehlend", pos: "adjective", en: "lacking, missing" },
      finanziellen: { lemma: "finanziell", pos: "adjective", en: "financial" },
      frühestmöglich: { lemma: "frühestmöglich", pos: "adverb", en: "as early as possible" },
      fördert: { lemma: "fördern", pos: "verb", en: "supports, promotes" },
      gebildet: { lemma: "bilden", pos: "verb", en: "educated" },
      gefördert: { lemma: "fördern", pos: "verb", en: "supported, promoted" },
      gegen: { lemma: "gegen", pos: "preposition", en: "against" },
      gegenseitig: { lemma: "gegenseitig", pos: "adverb", en: "mutually, each other" },
      genauso: { lemma: "genauso", pos: "adverb", en: "just as" },
      grundschule: { lemma: "die Grundschule", pos: "noun", en: "primary school" },
      gut: { lemma: "gut", pos: "adjective", en: "good, well" },
      gute: { lemma: "gut", pos: "adjective", en: "good" },
      gymnasialempfehlung: { lemma: "die Gymnasialempfehlung", pos: "noun", en: "recommendation for grammar school" },
      habe: { lemma: "haben", pos: "verb", en: "(I) have" },
      haben: { lemma: "haben", pos: "verb", en: "to have" },
      hat: { lemma: "haben", pos: "verb", en: "has" },
      hause: { lemma: "das Haus", pos: "noun", en: "home (zu Hause = at home)" },
      herkunft: { lemma: "die Herkunft", pos: "noun", en: "origin, background" },
      heute: { lemma: "heute", pos: "adverb", en: "today" },
      hier: { lemma: "hier", pos: "adverb", en: "here" },
      hängt: { lemma: "abhängen (von)", pos: "verb", en: "depends (hängt … ab)" },
      ich: { lemma: "ich", pos: "pronoun", en: "I" },
      ihr: { lemma: "ihr", pos: "pronoun", en: "her, their" },
      ihrer: { lemma: "ihrer", pos: "pronoun", en: "her, their" },
      im: { lemma: "im (in dem)", pos: "preposition", en: "in the" },
      immer: { lemma: "immer", pos: "adverb", en: "always (immer noch = still)" },
      in: { lemma: "in", pos: "preposition", en: "in" },
      individuell: { lemma: "individuell", pos: "adverb", en: "individually" },
      ist: { lemma: "sein", pos: "verb", en: "is" },
      jahren: { lemma: "das Jahr", pos: "noun", en: "years" },
      jahrgänge: { lemma: "der Jahrgang", pos: "noun", en: "year groups" },
      jedes: { lemma: "jedes", pos: "pronoun", en: "every (jedes dritte = every third)" },
      junge: { lemma: "jung", pos: "adjective", en: "young" },
      kam: { lemma: "kommen", pos: "verb", en: "came" },
      kann: { lemma: "können", pos: "verb", en: "can" },
      kein: { lemma: "kein", pos: "article", en: "no, not a" },
      keine: { lemma: "kein", pos: "article", en: "no, not any" },
      kennen: { lemma: "kennen", pos: "verb", en: "to know (kennenlernen = get to know)" },
      kettelerschule: { lemma: "die Kettelerschule", pos: "noun (proper)", en: "Ketteler School" },
      kind: { lemma: "das Kind", pos: "noun", en: "child" },
      kinder: { lemma: "das Kind", pos: "noun", en: "children" },
      kindern: { lemma: "das Kind", pos: "noun", en: "children (dative)" },
      kita: { lemma: "die Kita", pos: "noun", en: "daycare, nursery" },
      kitas: { lemma: "die Kita", pos: "noun", en: "daycares, nurseries" },
      klassen: { lemma: "die Klasse", pos: "noun", en: "grades, classes" },
      kommen: { lemma: "kommen", pos: "verb", en: "to come" },
      können: { lemma: "können", pos: "verb", en: "can, to be able to" },
      lag: { lemma: "liegen", pos: "verb", en: "was, ranked" },
      lang: { lemma: "Lang", pos: "noun (proper)", en: "Lang (name)" },
      lebensjahren: { lemma: "das Lebensjahr", pos: "noun", en: "years of life" },
      lehrerin: { lemma: "die Lehrerin", pos: "noun", en: "teacher (female)" },
      lehrerinnen: { lemma: "die Lehrerin", pos: "noun", en: "teachers (female)" },
      lehrern: { lemma: "der Lehrer", pos: "noun", en: "teachers" },
      leistungstests: { lemma: "der Leistungstest", pos: "noun", en: "performance tests" },
      lernen: { lemma: "lernen", pos: "verb", en: "to learn" },
      lernfamilien: { lemma: "die Lernfamilie", pos: "noun", en: "learning families" },
      lernt: { lemma: "lernen", pos: "verb", en: "learns (lernt kennen = gets to know)" },
      lesen: { lemma: "lesen / das Lesen", pos: "verb/noun", en: "to read; reading" },
      letzten: { lemma: "letzte", pos: "adjective", en: "last, recent" },
      ländern: { lemma: "das Land", pos: "noun", en: "countries" },
      macht: { lemma: "machen", pos: "verb", en: "makes, does" },
      man: { lemma: "man", pos: "pronoun", en: "one, you (impersonal)" },
      mit: { lemma: "mit", pos: "preposition", en: "with" },
      muss: { lemma: "müssen", pos: "verb", en: "must, has to" },
      möglichkeiten: { lemma: "die Möglichkeit", pos: "noun", en: "possibilities, opportunities" },
      nationale: { lemma: "national", pos: "adjective", en: "national" },
      neunjährige: { lemma: "der/die Neunjährige", pos: "noun", en: "nine-year-olds" },
      nicht: { lemma: "nicht", pos: "adverb", en: "not" },
      noch: { lemma: "noch", pos: "adverb", en: "still (immer noch = still)" },
      nrw: { lemma: "NRW", pos: "noun (proper)", en: "NRW (North Rhine-Westphalia)" },
      nur: { lemma: "nur", pos: "adverb", en: "only" },
      pro: { lemma: "pro", pos: "preposition", en: "per" },
      prozent: { lemma: "das Prozent", pos: "noun", en: "percent" },
      regelmäßigen: { lemma: "regelmäßig", pos: "adjective", en: "regular" },
      sagt: { lemma: "sagen", pos: "verb", en: "says" },
      schon: { lemma: "schon", pos: "adverb", en: "already" },
      schule: { lemma: "die Schule", pos: "noun", en: "school" },
      schulkinder: { lemma: "das Schulkind", pos: "noun", en: "schoolchildren" },
      schulleiterin: { lemma: "die Schulleiterin", pos: "noun", en: "headmistress" },
      schüler: { lemma: "der Schüler", pos: "noun", en: "pupils, students" },
      schülerinnen: { lemma: "die Schülerin", pos: "noun", en: "female pupils, students" },
      sechs: { lemma: "sechs", pos: "numeral", en: "six (Sechs- = six-year-olds)" },
      sehr: { lemma: "sehr", pos: "adverb", en: "very" },
      sich: { lemma: "sich", pos: "pronoun", en: "oneself, each other" },
      sie: { lemma: "sie", pos: "pronoun", en: "they, she" },
      so: { lemma: "so", pos: "adverb", en: "so, thus" },
      sogenannten: { lemma: "sogenannt", pos: "adjective", en: "so-called" },
      sonderpädagogen: { lemma: "der Sonderpädagoge", pos: "noun", en: "special-needs educators" },
      sowie: { lemma: "sowie", pos: "conjunction", en: "as well as" },
      sozial: { lemma: "sozial", pos: "adjective", en: "social (Sozialpädagogen)" },
      sozialen: { lemma: "sozial", pos: "adjective", en: "social" },
      sprache: { lemma: "die Sprache", pos: "noun", en: "language" },
      sprachförderung: { lemma: "die Sprachförderung", pos: "noun", en: "language support" },
      sprechen: { lemma: "sprechen", pos: "verb", en: "speak" },
      später: { lemma: "später", pos: "adverb", en: "later" },
      stark: { lemma: "stark", pos: "adverb", en: "strongly" },
      stellenwert: { lemma: "der Stellenwert", pos: "noun", en: "importance, status" },
      team: { lemma: "das Team", pos: "noun", en: "team" },
      trotzdem: { lemma: "trotzdem", pos: "adverb", en: "nevertheless" },
      tun: { lemma: "tun", pos: "verb", en: "to do" },
      umliegenden: { lemma: "umliegend", pos: "adjective", en: "surrounding, nearby" },
      und: { lemma: "und", pos: "conjunction", en: "and" },
      ungleichheit: { lemma: "die Ungleichheit", pos: "noun", en: "inequality" },
      unsere: { lemma: "unser", pos: "pronoun", en: "our" },
      unterrichtet: { lemma: "unterrichten", pos: "verb", en: "taught" },
      unterstützen: { lemma: "unterstützen", pos: "verb", en: "to support" },
      vergleich: { lemma: "der Vergleich", pos: "noun", en: "comparison (im Vergleich = in comparison)" },
      viel: { lemma: "viel", pos: "adverb/adjective", en: "much, a lot" },
      viele: { lemma: "viele", pos: "pronoun", en: "many" },
      von: { lemma: "von", pos: "preposition", en: "of, from" },
      vor: { lemma: "vor", pos: "preposition", en: "before, in front of" },
      vorher: { lemma: "vorher", pos: "adverb", en: "beforehand" },
      vorschulkinder: { lemma: "das Vorschulkind", pos: "noun", en: "preschool children" },
      waren: { lemma: "sein", pos: "verb", en: "were" },
      was: { lemma: "was", pos: "pronoun", en: "what" },
      weiteren: { lemma: "weitere", pos: "adjective", en: "further" },
      welchen: { lemma: "welchen", pos: "pronoun", en: "which" },
      wenn: { lemma: "wenn", pos: "conjunction", en: "if, when" },
      werden: { lemma: "werden", pos: "verb", en: "to be (passive), become" },
      wie: { lemma: "wie", pos: "conjunction/adverb", en: "like, as, how" },
      will: { lemma: "wollen", pos: "verb", en: "wants to" },
      winter: { lemma: "Winter", pos: "noun (proper)", en: "Winter (name, Lang-Winter)" },
      wird: { lemma: "werden", pos: "verb", en: "is (being), will" },
      woche: { lemma: "die Woche", pos: "noun", en: "week" },
      zeigt: { lemma: "zeigen", pos: "verb", en: "shows" },
      zu: { lemma: "zu", pos: "preposition", en: "to, too (zu Hause = at home)" },
      zusammen: { lemma: "zusammen", pos: "adverb", en: "together" },
      zuwanderungsgeschichte: { lemma: "die Zuwanderungsgeschichte", pos: "noun", en: "immigration background" },
      zweimal: { lemma: "zweimal", pos: "adverb", en: "twice" },
      ändern: { lemma: "ändern", pos: "verb", en: "to change" },
      über: { lemma: "über", pos: "preposition", en: "over, above" },
    },
    sentences: {
      "Wie gut ein Kind in der Schule ist und welchen Abschluss es macht, hängt in Deutschland immer noch stark von der sozialen Herkunft ab.":
        "How well a child does at school and what qualification it obtains still depends strongly on social background in Germany.",
      "Eine Grundschule in Bonn zeigt, dass man daran etwas ändern kann.":
        "A primary school in Bonn shows that this can be changed.",
      "Im Vergleich zu anderen Ländern hängt in Deutschland der Bildungserfolg immer noch stark von der sozialen Herkunft, den finanziellen Möglichkeiten und der Bildung der Familien ab.":
        "Compared to other countries, educational success in Germany still depends strongly on social background, financial means and the education of families.",
      "Der Nationale Bildungsbericht 2026 zeigt, dass diese Ungleichheit bereits in den ersten Lebensjahren entsteht und dann den weiteren Bildungsweg von Kindern beeinflusst.":
        "The National Education Report 2026 shows that this inequality already arises in the first years of life and then influences children's further educational path.",
      "Was kann man gegen die fehlende Chancengerechtigkeit tun?":
        "What can be done about the lack of equal opportunity?",
      "Fast alle 250 Schülerinnen und Schüler der Bonner Kettelerschule haben eine Zuwanderungsgeschichte, viele sprechen zu Hause kein Deutsch und jedes dritte Kind muss besonders gefördert werden.":
        "Almost all 250 pupils at the Ketteler School in Bonn have an immigration background, many speak no German at home, and every third child needs special support.",
      "Trotzdem lag die Schule in den letzten Jahren bei Leistungstests im Bundesland NRW über dem Durchschnitt.":
        "Nevertheless, in recent years the school ranked above average in performance tests in the federal state of NRW.",
      "„Ich will, dass unsere Kinder hier alles lernen können, damit sie später genauso gute Chancen haben wie Kinder aus Elternhäusern, in denen Kindern von Anfang an sehr viel ermöglicht wird\", sagt Schulleiterin Christina Lang-Winter, die 2004 als junge Lehrerin an die Schule kam.":
        "\"I want our children to be able to learn everything here, so that they later have just as good opportunities as children from homes where a great deal is made possible for children from the very start\", says headmistress Christina Lang-Winter, who came to the school in 2004 as a young teacher.",
      "In der Kettelerschule lernen die Kinder in sogenannten „Lernfamilien\".":
        "At the Ketteler School, the children learn in so-called \"learning families\".",
      "Das bedeutet, dass Jahrgänge zusammen unterrichtet werden und sich so Sechs- und Neunjährige gegenseitig unterstützen.":
        "That means that year groups are taught together and so six- and nine-year-olds support each other.",
      "Außerdem arbeitet an der Grundschule ein Team aus Lehrerinnen und Lehrern sowie Sozial- und Sonderpädagogen eng zusammen und fördert die Kinder individuell.":
        "In addition, at the primary school a team of teachers as well as social and special-needs educators works closely together and supports the children individually.",
      "Vor allem in den ersten Klassen hat das Lesen einen besonderen Stellenwert – und Sprache im Allgemeinen: „Wenn ich keine Sprache habe, kann ich auch nicht gebildet werden\", so Lang-Winter.":
        "Above all in the first grades, reading has a special importance, and language in general: \"If I have no language, I cannot be educated either\", says Lang-Winter.",
      "Die Sprachförderung beginnt bei ihr aber schon vor der Einschulung.":
        "Her language support begins even before school enrollment, though.",
      "Dafür ist die Schule mit umliegenden Kitas im regelmäßigen Austausch: Schulkinder lesen in der Kita vor, und die Vorschulkinder aus der Kita kommen zweimal pro Woche in die Grundschule.":
        "For this, the school is in regular exchange with nearby daycare centers: schoolchildren read aloud at the daycare, and the preschool children from the daycare come to the primary school twice a week.",
      "So lernt man die Kinder schon vorher kennen und kann sie frühestmöglich unterstützen, erklärt die Schulleiterin.":
        "This way, you get to know the children beforehand and can support them as early as possible, the headmistress explains.",
      "Mit Erfolg: Heute bekommen 30 Prozent ihrer Schülerinnen und Schüler eine Gymnasialempfehlung, 2007 waren es nur 0,5 Prozent.":
        "With success: today 30 percent of her pupils receive a recommendation for grammar school, in 2007 it was only 0.5 percent.",
    },
  },
  {
    id: "pestizide",
    category: "Umwelt",
    level: "B2",
    photo: "https://picsum.photos/seed/pestizide/600/400",
    title: "Pestizide per Drohne: eine gute Lösung?",
    desc: "Drohnen sollen Pestizide sparen – Fachleute sind skeptisch.",
    paragraphs: [
      `Pestizide aus der Luft auf Felder zu sprühen, war in der EU lange verboten. Das ändert sich jetzt: Bald sollen Drohnen dabei helfen, dass weniger Pestizide verbraucht werden. Fachleute kritisieren das.`,
      `Keine Fahrzeuge, die über das ganze Feld fahren, sondern Drohnen, die Pestizide sprühen – nur dort, wo sie gebraucht werden. So könnte Pflanzenschutz in Zukunft aussehen. In der EU war es jahrzehntelang verboten, Pestizide aus der Luft auf landwirtschaftliche Flächen zu sprühen. Mit einem neuen Gesetzgebungspaket soll sich das nun ändern. Die EU hofft, mit Drohnen den Verbrauch chemischer Pflanzenschutzmittel bis 2030 zu halbieren.`,
      `Vorteile sieht auch der Agrarökonom Thomas Daun: Die Landwirtschaft kann damit schnell auf Schädlinge reagieren, und das „auch bei nassen Böden" oder auf Flächen, die mit Fahrzeugen nur schwer zu erreichen sind, so Daun. Außerdem könnten Drohnen im Vergleich zu Flugzeugen sehr viel genauer arbeiten. Allerdings warnt Daun auch: „Die Drohne selbst spart noch kein Pestizid." Ein flexiblerer Einsatz von Pestiziden könnte sogar dazu führen, dass die Mittel häufiger benutzt werden und die Landwirtschaft stärker von ihnen abhängig wird.`,
      `Hinzu kommt: Die EU will auch die Zulassung von Pestiziden vereinfachen und so Verwaltungskosten reduzieren. Wissenschaftler wie der Biologe Carsten Brühl nennen das „fahrlässig". Wenn Pestizide nach ihrer Zulassung seltener geprüft werden, könnten auch gesundheitsschädliche Mittel länger eingesetzt werden. Denn oft sieht man erst in der Praxis, welche Folgen Pestizide für die Umwelt und den Menschen haben, so Brühl.`,
      `Dass Landwirtschaft auch ohne Pestizide möglich ist, zeigt der „integrierte Pflanzenschutz". Dabei werden zum Beispiel verschiedene Pflanzen auf einem Feld angebaut, so dass Schädlinge weniger Nahrung an einem Ort finden. Statt Chemie helfen außerdem natürliche Fressfeinde. Das kostet zwar mehr Zeit und damit Geld, schützt aber das Ökosystem und macht die Landwirtschaft widerstandsfähiger. Auch gegen den Klimawandel.`,
    ],
    glossary: {
      pestizide: { lemma: "das Pestizid", pos: "noun", en: "pesticides" },
      drohne: { lemma: "die Drohne", pos: "noun", en: "drone" },
      drohnen: { lemma: "die Drohne", pos: "noun", en: "drones" },
      lösung: { lemma: "die Lösung", pos: "noun", en: "solution" },
      sprühen: { lemma: "sprühen", pos: "verb", en: "to spray" },
      felder: { lemma: "das Feld", pos: "noun", en: "fields" },
      verboten: { lemma: "verbieten", pos: "verb", en: "forbidden, banned" },
      pflanzenschutz: { lemma: "der Pflanzenschutz", pos: "noun", en: "crop protection" },
      verbrauch: { lemma: "der Verbrauch", pos: "noun", en: "consumption" },
      halbieren: { lemma: "halbieren", pos: "verb", en: "to halve" },
      schädlinge: { lemma: "der Schädling", pos: "noun", en: "pests" },
      reagieren: { lemma: "reagieren", pos: "verb", en: "to react" },
      böden: { lemma: "der Boden", pos: "noun", en: "soils" },
      einsatz: { lemma: "der Einsatz", pos: "noun", en: "use, deployment" },
      abhängig: { lemma: "abhängig", pos: "adjective", en: "dependent" },
      zulassung: { lemma: "die Zulassung", pos: "noun", en: "authorization, approval" },
      fahrlässig: { lemma: "fahrlässig", pos: "adjective", en: "negligent" },
      umwelt: { lemma: "die Umwelt", pos: "noun", en: "environment" },
      fressfeinde: { lemma: "der Fressfeind", pos: "noun", en: "natural predators" },
      ökosystem: { lemma: "das Ökosystem", pos: "noun", en: "ecosystem" },
      klimawandel: { lemma: "der Klimawandel", pos: "noun", en: "climate change" },
    },
    words: {
      "2030": { lemma: "2030", pos: "numeral", en: "2030 (year)" },
      aber: { lemma: "aber", pos: "conjunction", en: "but" },
      abhängig: { lemma: "abhängig", pos: "adjective", en: "dependent" },
      agrarökonom: { lemma: "der Agrarökonom", pos: "noun", en: "agricultural economist" },
      allerdings: { lemma: "allerdings", pos: "adverb", en: "however, though" },
      an: { lemma: "an", pos: "preposition", en: "at, on (an einem Ort = in one place)" },
      angebaut: { lemma: "anbauen", pos: "verb", en: "grown, cultivated" },
      arbeiten: { lemma: "arbeiten", pos: "verb", en: "to work" },
      auch: { lemma: "auch", pos: "adverb", en: "also, too" },
      auf: { lemma: "auf", pos: "preposition", en: "on, onto" },
      aus: { lemma: "aus", pos: "preposition", en: "from, out of" },
      aussehen: { lemma: "aussehen", pos: "verb", en: "to look (like)" },
      außerdem: { lemma: "außerdem", pos: "adverb", en: "besides, in addition" },
      bald: { lemma: "bald", pos: "adverb", en: "soon" },
      bei: { lemma: "bei", pos: "preposition", en: "at, with, in the case of" },
      beispiel: { lemma: "das Beispiel", pos: "noun", en: "example" },
      benutzt: { lemma: "benutzen", pos: "verb", en: "used" },
      biologe: { lemma: "der Biologe", pos: "noun", en: "biologist" },
      bis: { lemma: "bis", pos: "preposition", en: "until, by" },
      brühl: { lemma: "Brühl", pos: "noun (proper)", en: "Brühl (name)" },
      böden: { lemma: "der Boden", pos: "noun", en: "soils" },
      carsten: { lemma: "Carsten", pos: "noun (proper)", en: "Carsten (name)" },
      chemie: { lemma: "die Chemie", pos: "noun", en: "chemistry, chemicals" },
      chemischer: { lemma: "chemisch", pos: "adjective", en: "chemical" },
      dabei: { lemma: "dabei", pos: "adverb", en: "in doing so, here" },
      damit: { lemma: "damit", pos: "adverb", en: "with it (und damit = and thus)" },
      das: { lemma: "das", pos: "article/pronoun", en: "the, that" },
      dass: { lemma: "dass", pos: "conjunction", en: "that" },
      daun: { lemma: "Daun", pos: "noun (proper)", en: "Daun (name)" },
      dazu: { lemma: "dazu", pos: "adverb", en: "to it (dazu führen = to lead to)" },
      den: { lemma: "den", pos: "article", en: "the" },
      denn: { lemma: "denn", pos: "conjunction", en: "because, for" },
      der: { lemma: "der", pos: "article", en: "the" },
      die: { lemma: "die", pos: "article", en: "the" },
      dort: { lemma: "dort", pos: "adverb", en: "there" },
      drohne: { lemma: "die Drohne", pos: "noun", en: "drone" },
      drohnen: { lemma: "die Drohne", pos: "noun", en: "drones" },
      ein: { lemma: "ein", pos: "article", en: "a, an" },
      einem: { lemma: "einem", pos: "article", en: "a (dative)" },
      eingesetzt: { lemma: "einsetzen", pos: "verb", en: "used, deployed" },
      einsatz: { lemma: "der Einsatz", pos: "noun", en: "use, deployment" },
      erreichen: { lemma: "erreichen", pos: "verb", en: "to reach" },
      erst: { lemma: "erst", pos: "adverb", en: "only, not until" },
      es: { lemma: "es", pos: "pronoun", en: "it" },
      eu: { lemma: "die EU", pos: "noun (proper)", en: "the EU" },
      fachleute: { lemma: "die Fachleute", pos: "noun (pl.)", en: "experts" },
      fahren: { lemma: "fahren", pos: "verb", en: "to drive" },
      fahrlässig: { lemma: "fahrlässig", pos: "adjective", en: "negligent" },
      fahrzeuge: { lemma: "das Fahrzeug", pos: "noun", en: "vehicles" },
      fahrzeugen: { lemma: "das Fahrzeug", pos: "noun", en: "vehicles (dative)" },
      feld: { lemma: "das Feld", pos: "noun", en: "field" },
      felder: { lemma: "das Feld", pos: "noun", en: "fields" },
      finden: { lemma: "finden", pos: "verb", en: "to find" },
      flexiblerer: { lemma: "flexibel", pos: "adjective", en: "more flexible" },
      flugzeugen: { lemma: "das Flugzeug", pos: "noun", en: "airplanes" },
      flächen: { lemma: "die Fläche", pos: "noun", en: "areas, surfaces" },
      folgen: { lemma: "die Folge", pos: "noun", en: "consequences" },
      fressfeinde: { lemma: "der Fressfeind", pos: "noun", en: "natural predators" },
      führen: { lemma: "führen", pos: "verb", en: "to lead (dazu führen = to result in)" },
      für: { lemma: "für", pos: "preposition", en: "for" },
      ganze: { lemma: "ganz", pos: "adjective", en: "whole, entire" },
      gebraucht: { lemma: "brauchen", pos: "verb", en: "needed" },
      gegen: { lemma: "gegen", pos: "preposition", en: "against" },
      geld: { lemma: "das Geld", pos: "noun", en: "money" },
      genauer: { lemma: "genau", pos: "adjective", en: "more precisely" },
      geprüft: { lemma: "prüfen", pos: "verb", en: "checked, tested" },
      gesetzgebungspaket: { lemma: "das Gesetzgebungspaket", pos: "noun", en: "legislative package" },
      gesundheitsschädliche: { lemma: "gesundheitsschädlich", pos: "adjective", en: "harmful to health" },
      haben: { lemma: "haben", pos: "verb", en: "to have" },
      halbieren: { lemma: "halbieren", pos: "verb", en: "to halve" },
      helfen: { lemma: "helfen", pos: "verb", en: "to help" },
      hinzu: { lemma: "hinzu", pos: "adverb", en: "in addition (hinzu kommt = added to this)" },
      hofft: { lemma: "hoffen", pos: "verb", en: "hopes" },
      häufiger: { lemma: "häufig", pos: "adverb", en: "more often" },
      ihnen: { lemma: "ihnen", pos: "pronoun", en: "them" },
      ihrer: { lemma: "ihrer", pos: "pronoun", en: "their (nach ihrer Zulassung)" },
      im: { lemma: "im (in dem)", pos: "preposition", en: "in the" },
      in: { lemma: "in", pos: "preposition", en: "in" },
      integrierte: { lemma: "integriert", pos: "adjective", en: "integrated" },
      ist: { lemma: "sein", pos: "verb", en: "is" },
      jahrzehntelang: { lemma: "jahrzehntelang", pos: "adverb", en: "for decades" },
      jetzt: { lemma: "jetzt", pos: "adverb", en: "now" },
      kann: { lemma: "können", pos: "verb", en: "can" },
      kein: { lemma: "kein", pos: "article", en: "no, not a" },
      keine: { lemma: "kein", pos: "article", en: "no, not any" },
      klimawandel: { lemma: "der Klimawandel", pos: "noun", en: "climate change" },
      kommt: { lemma: "kommen", pos: "verb", en: "comes (hinzu kommt = added to this)" },
      kostet: { lemma: "kosten", pos: "verb", en: "costs" },
      kritisieren: { lemma: "kritisieren", pos: "verb", en: "to criticize" },
      könnte: { lemma: "können", pos: "verb", en: "could" },
      könnten: { lemma: "können", pos: "verb", en: "could" },
      landwirtschaft: { lemma: "die Landwirtschaft", pos: "noun", en: "agriculture, farming" },
      landwirtschaftliche: { lemma: "landwirtschaftlich", pos: "adjective", en: "agricultural" },
      lange: { lemma: "lange", pos: "adverb", en: "for a long time" },
      luft: { lemma: "die Luft", pos: "noun", en: "air" },
      länger: { lemma: "lang", pos: "adjective", en: "longer" },
      macht: { lemma: "machen", pos: "verb", en: "makes" },
      man: { lemma: "man", pos: "pronoun", en: "one, you (impersonal)" },
      mehr: { lemma: "mehr", pos: "adverb", en: "more" },
      menschen: { lemma: "der Mensch", pos: "noun", en: "people, humans" },
      mit: { lemma: "mit", pos: "preposition", en: "with" },
      mittel: { lemma: "das Mittel", pos: "noun", en: "agents, means (here: pesticides)" },
      möglich: { lemma: "möglich", pos: "adjective", en: "possible" },
      nach: { lemma: "nach", pos: "preposition", en: "after" },
      nahrung: { lemma: "die Nahrung", pos: "noun", en: "food, nourishment" },
      nassen: { lemma: "nass", pos: "adjective", en: "wet" },
      natürliche: { lemma: "natürlich", pos: "adjective", en: "natural" },
      nennen: { lemma: "nennen", pos: "verb", en: "to call" },
      neuen: { lemma: "neu", pos: "adjective", en: "new" },
      noch: { lemma: "noch", pos: "adverb", en: "still, yet" },
      nun: { lemma: "nun", pos: "adverb", en: "now" },
      nur: { lemma: "nur", pos: "adverb", en: "only" },
      oder: { lemma: "oder", pos: "conjunction", en: "or" },
      oft: { lemma: "oft", pos: "adverb", en: "often" },
      ohne: { lemma: "ohne", pos: "preposition", en: "without" },
      ort: { lemma: "der Ort", pos: "noun", en: "place (an einem Ort = in one place)" },
      pestizid: { lemma: "das Pestizid", pos: "noun", en: "pesticide" },
      pestizide: { lemma: "das Pestizid", pos: "noun", en: "pesticides" },
      pestiziden: { lemma: "das Pestizid", pos: "noun", en: "pesticides (dative)" },
      pflanzen: { lemma: "die Pflanze", pos: "noun", en: "plants" },
      pflanzenschutz: { lemma: "der Pflanzenschutz", pos: "noun", en: "crop protection" },
      pflanzenschutzmittel: { lemma: "das Pflanzenschutzmittel", pos: "noun", en: "crop-protection products" },
      praxis: { lemma: "die Praxis", pos: "noun", en: "practice" },
      reagieren: { lemma: "reagieren", pos: "verb", en: "to react" },
      reduzieren: { lemma: "reduzieren", pos: "verb", en: "to reduce" },
      schnell: { lemma: "schnell", pos: "adjective/adverb", en: "quick, quickly" },
      schwer: { lemma: "schwer", pos: "adjective", en: "difficult, hard" },
      schädlinge: { lemma: "der Schädling", pos: "noun", en: "pests" },
      schützt: { lemma: "schützen", pos: "verb", en: "protects" },
      sehr: { lemma: "sehr", pos: "adverb", en: "very" },
      selbst: { lemma: "selbst", pos: "adverb/pronoun", en: "itself, even" },
      seltener: { lemma: "selten", pos: "adverb", en: "less often" },
      sich: { lemma: "sich", pos: "pronoun", en: "oneself" },
      sie: { lemma: "sie", pos: "pronoun", en: "they" },
      sieht: { lemma: "sehen", pos: "verb", en: "sees (sieht … aus = looks)" },
      sind: { lemma: "sein", pos: "verb", en: "are" },
      so: { lemma: "so", pos: "adverb", en: "so, thus" },
      sogar: { lemma: "sogar", pos: "adverb", en: "even" },
      soll: { lemma: "sollen", pos: "verb", en: "is supposed to, should" },
      sollen: { lemma: "sollen", pos: "verb", en: "are supposed to, should" },
      sondern: { lemma: "sondern", pos: "conjunction", en: "but (rather)" },
      spart: { lemma: "sparen", pos: "verb", en: "saves" },
      sprühen: { lemma: "sprühen", pos: "verb", en: "to spray" },
      statt: { lemma: "statt", pos: "preposition", en: "instead of" },
      stärker: { lemma: "stark", pos: "adjective", en: "more strongly" },
      thomas: { lemma: "Thomas", pos: "noun (proper)", en: "Thomas (name)" },
      umwelt: { lemma: "die Umwelt", pos: "noun", en: "environment" },
      und: { lemma: "und", pos: "conjunction", en: "and" },
      verboten: { lemma: "verbieten", pos: "verb", en: "forbidden, banned" },
      verbrauch: { lemma: "der Verbrauch", pos: "noun", en: "consumption" },
      verbraucht: { lemma: "verbrauchen", pos: "verb", en: "consumed, used up" },
      vereinfachen: { lemma: "vereinfachen", pos: "verb", en: "to simplify" },
      vergleich: { lemma: "der Vergleich", pos: "noun", en: "comparison (im Vergleich = in comparison)" },
      verschiedene: { lemma: "verschieden", pos: "adjective", en: "different, various" },
      verwaltungskosten: { lemma: "die Verwaltungskosten", pos: "noun (pl.)", en: "administrative costs" },
      viel: { lemma: "viel", pos: "adverb/adjective", en: "much, a lot" },
      von: { lemma: "von", pos: "preposition", en: "of, from" },
      vorteile: { lemma: "der Vorteil", pos: "noun", en: "advantages" },
      war: { lemma: "sein", pos: "verb", en: "was" },
      warnt: { lemma: "warnen", pos: "verb", en: "warns" },
      welche: { lemma: "welche", pos: "pronoun", en: "which, what" },
      weniger: { lemma: "weniger", pos: "adverb", en: "less, fewer" },
      wenn: { lemma: "wenn", pos: "conjunction", en: "if, when" },
      werden: { lemma: "werden", pos: "verb", en: "to be (passive), will" },
      widerstandsfähiger: { lemma: "widerstandsfähig", pos: "adjective", en: "more resilient" },
      wie: { lemma: "wie", pos: "conjunction/adverb", en: "like, as, how" },
      will: { lemma: "wollen", pos: "verb", en: "wants to" },
      wird: { lemma: "werden", pos: "verb", en: "is (being), will, becomes" },
      wissenschaftler: { lemma: "der Wissenschaftler", pos: "noun", en: "scientists" },
      wo: { lemma: "wo", pos: "adverb", en: "where" },
      zeigt: { lemma: "zeigen", pos: "verb", en: "shows" },
      zeit: { lemma: "die Zeit", pos: "noun", en: "time" },
      zu: { lemma: "zu", pos: "preposition", en: "to, too" },
      zukunft: { lemma: "die Zukunft", pos: "noun", en: "future" },
      zulassung: { lemma: "die Zulassung", pos: "noun", en: "authorization, approval" },
      zum: { lemma: "zum (zu dem)", pos: "preposition", en: "to the (zum Beispiel = for example)" },
      zwar: { lemma: "zwar", pos: "adverb", en: "admittedly (zwar … aber = it's true … but)" },
      ändern: { lemma: "ändern", pos: "verb", en: "to change" },
      ändert: { lemma: "ändern", pos: "verb", en: "changes (ändert sich = is changing)" },
      ökosystem: { lemma: "das Ökosystem", pos: "noun", en: "ecosystem" },
      über: { lemma: "über", pos: "preposition", en: "over, across" },
    },
    sentences: {
      "Pestizide aus der Luft auf Felder zu sprühen, war in der EU lange verboten.":
        "Spraying pesticides onto fields from the air was banned in the EU for a long time.",
      "Das ändert sich jetzt: Bald sollen Drohnen dabei helfen, dass weniger Pestizide verbraucht werden.":
        "That is changing now: soon drones are meant to help ensure that fewer pesticides are used.",
      "Fachleute kritisieren das.":
        "Experts criticize this.",
      "Keine Fahrzeuge, die über das ganze Feld fahren, sondern Drohnen, die Pestizide sprühen – nur dort, wo sie gebraucht werden.":
        "Not vehicles that drive across the whole field, but drones that spray pesticides, only where they are needed.",
      "So könnte Pflanzenschutz in Zukunft aussehen.":
        "That is how crop protection could look in the future.",
      "In der EU war es jahrzehntelang verboten, Pestizide aus der Luft auf landwirtschaftliche Flächen zu sprühen.":
        "In the EU it was banned for decades to spray pesticides onto agricultural land from the air.",
      "Mit einem neuen Gesetzgebungspaket soll sich das nun ändern.":
        "With a new legislative package, this is now set to change.",
      "Die EU hofft, mit Drohnen den Verbrauch chemischer Pflanzenschutzmittel bis 2030 zu halbieren.":
        "The EU hopes to halve the consumption of chemical crop-protection products by 2030 with drones.",
      "Vorteile sieht auch der Agrarökonom Thomas Daun: Die Landwirtschaft kann damit schnell auf Schädlinge reagieren, und das „auch bei nassen Böden\" oder auf Flächen, die mit Fahrzeugen nur schwer zu erreichen sind, so Daun.":
        "The agricultural economist Thomas Daun also sees advantages: agriculture can react quickly to pests with them, and that \"even on wet soils\" or on areas that are hard to reach with vehicles, says Daun.",
      "Außerdem könnten Drohnen im Vergleich zu Flugzeugen sehr viel genauer arbeiten.":
        "Moreover, compared to airplanes, drones could work much more precisely.",
      "Allerdings warnt Daun auch: „Die Drohne selbst spart noch kein Pestizid.\" Ein flexiblerer Einsatz von Pestiziden könnte sogar dazu führen, dass die Mittel häufiger benutzt werden und die Landwirtschaft stärker von ihnen abhängig wird.":
        "However, Daun also warns: \"The drone itself does not yet save any pesticide.\" A more flexible use of pesticides could even lead to the agents being used more often and agriculture becoming more dependent on them.",
      "Hinzu kommt: Die EU will auch die Zulassung von Pestiziden vereinfachen und so Verwaltungskosten reduzieren.":
        "In addition: the EU also wants to simplify the authorization of pesticides and thus reduce administrative costs.",
      "Wissenschaftler wie der Biologe Carsten Brühl nennen das „fahrlässig\".":
        "Scientists like the biologist Carsten Brühl call this \"negligent\".",
      "Wenn Pestizide nach ihrer Zulassung seltener geprüft werden, könnten auch gesundheitsschädliche Mittel länger eingesetzt werden.":
        "If pesticides are checked less often after their authorization, harmful agents could also be used for longer.",
      "Denn oft sieht man erst in der Praxis, welche Folgen Pestizide für die Umwelt und den Menschen haben, so Brühl.":
        "Because often you only see in practice what consequences pesticides have for the environment and for people, says Brühl.",
      "Dass Landwirtschaft auch ohne Pestizide möglich ist, zeigt der „integrierte Pflanzenschutz\".":
        "That farming is also possible without pesticides is shown by \"integrated crop protection\".",
      "Dabei werden zum Beispiel verschiedene Pflanzen auf einem Feld angebaut, so dass Schädlinge weniger Nahrung an einem Ort finden.":
        "In this, for example, different plants are grown on one field, so that pests find less food in one place.",
      "Statt Chemie helfen außerdem natürliche Fressfeinde.":
        "Instead of chemicals, natural predators also help.",
      "Das kostet zwar mehr Zeit und damit Geld, schützt aber das Ökosystem und macht die Landwirtschaft widerstandsfähiger.":
        "This does cost more time and thus money, but it protects the ecosystem and makes agriculture more resilient.",
      "Auch gegen den Klimawandel.":
        "Against climate change too.",
    },
  },
];

export const textById = (id) => texts.find((t) => t.id === id);
